import avatarProfile from '../../public/image/imgProfile.png';
const userStories = [
      {
        id:1,
        avatarUser:`${avatarProfile}`,
        name:"User1"
      },
      {
        id:2,
        avatarUser:`${avatarProfile}`,
        name:"User2"
      },
      {
        id:3,
        avatarUser:`${avatarProfile}`,
        name:"User3"
      },
      {
        id:4,
        avatarUser:`${avatarProfile}`,
        name:"User4"
      },
      {
        id:5,
        avatarUser:`${avatarProfile}`,
        name:"User5"
      },
      {
        id:6,
        avatarUser:`${avatarProfile}`,
        name:"User6"
      },
      {
        id:7,
        avatarUser:`${avatarProfile}`,
        name:"User7"
      },
      {
        id:8,
        avatarUser:`${avatarProfile}`,
        name:"User8"
      },
      {
        id:9,
        avatarUser:`${avatarProfile}`,
        name:"User9"
      },
      {
        id:10,
        avatarUser:`${avatarProfile}`,
        name:"User10"
      }
]

export {
    userStories
}